services:
  database:
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DATABASE_URL"]
      interval: 10s
      timeout: 5s
      retries: 10
    image: postgres:alpine
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - $DATABASE_PATH:/var/lib/postgresql/data

  database.migrate:
    command: ["-path", "/migrations", "-database", "$DATABASE_URL", "up"]
    depends_on:
      database:
        condition: service_healthy
    image: migrate/migrate
    volumes:
      - $MIGRATIONS_PATH:/migrations

  database.seed:
    build: $SCRIPTS_PATH/database-seed
    depends_on:
      database:
        condition: service_healthy
    environment:
      ARTIFACTS_PATH: $ARTIFACTS_PATH
      DATABASE_URL: $DATABASE_URL
    volumes:
      - $ARTIFACTS_PATH:/app/artifacts
